# Generated by Django 4.2.10 on 2024-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics_todo', '0002_alter_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_owner_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
